FROM node:21
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

# add npm installs here
RUN npm install && npm install cors && npm install react-scripts@3.4.1 -g --silent
CMD ["npm", "run", "dev"]
